apiVersion: apps/v1

kind: Deployment

metadata:

  name: demo-angular

spec:

  replicas: 2

  selector:

    matchLabels:

      app: demo-angular

  template:

    metadata:

      labels:

        app: demo-angular

    spec:

      containers:
      - name: demo-angular
        image: cicdangularregistery.azurecr.io/angularcicd:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth-secret

 